### ISSUE TITLE
Error when importing QtMultimedia on Travis

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#111]
I'm getting this error in TravisCI (which is not seen locally):
```
ImportError: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory
```
This error occurs when importing QtMultimedia:

```
$ python --version
Python 3.6.3
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (python 3.6)
install.1
20.07s$ pip install -r requirements.txt
Collecting PyQt5==5.9 (from -r requirements.txt (line 1))
  Downloading PyQt5-5.9-5.9.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (104.6MB)
Collecting sip==4.19.3 (from -r requirements.txt (line 2))
  Downloading sip-4.19.3-cp36-cp36m-manylinux1_x86_64.whl (63kB)
Installing collected packages: sip, PyQt5
Successfully installed PyQt5-5.9 sip-4.19.3
install.2
2.04s$ pip install coverage
Collecting coverage
  Downloading coverage-4.4.2-cp36-cp36m-manylinux1_x86_64.whl (197kB)
Installing collected packages: coverage
Successfully installed coverage-4.4.2
install.3
3.75s$ pip install codecov
Collecting codecov
  Downloading codecov-2.0.10-py2.py3-none-any.whl
Collecting requests>=2.7.9 (from codecov)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Requirement already satisfied: coverage in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from codecov)
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.7.9->codecov)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.7.9->codecov)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna<2.7,>=2.5 (from requests>=2.7.9->codecov)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Collecting certifi>=2017.4.17 (from requests>=2.7.9->codecov)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
Installing collected packages: urllib3, chardet, idna, certifi, requests, codecov
Successfully installed certifi-2017.11.5 chardet-3.0.4 codecov-2.0.10 idna-2.6 requests-2.18.4 urllib3-1.22
before_script.1
0.01s$ export DISPLAY=:99.0
before_script.2
0.02s$ sh -e /etc/init.d/xvfb start
Starting virtual X frame buffer: Xvfb.
before_script.3
3.01s$ sleep 3
0.55s$ coverage run --source=. -m unittest discover -s test
E
======================================================================
ERROR: test_main (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_main
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/mindfulness-at-the-computer/mindfulness-at-the-computer/test/test_main.py", line 12, in <module>
    import mc.gui.main_win
  File "/home/travis/build/mindfulness-at-the-computer/mindfulness-at-the-computer/mc/gui/main_win.py", line 6, in <module>
    from PyQt5 import QtMultimedia
ImportError: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory
```

**Comment by SunyataZero** [comment]
Solution 1: Switch to a "sudo setup" in Travis and install the `libpulse-dev` package

**Comment by SunyataZero** [comment]
Solution 2: Wrap import statement and any code using the import inside `try` + `except` statements

**Comment by SunyataZero** [comment]
Solution 3: Load a fake sound driver

https://stackoverflow.com/questions/15859196/travisci-no-audio-device

Example .travis config: https://travis-ci.org/k3it/qsorder/jobs/112413932/config
