### ISSUE TITLE
Crash in Settings on selecting an Action and clicking Edit button

### ISSUE THREAD

**Issue by milkmiruku** [mindfulness-at-the-computer/mindfulness-at-the-computer#309]
```
Traceback (most recent call last):
  File "/home/milk/src/mindfulness-at-the-computer/mc/gui/rest_action_list_wt.py", line 81, in on_edit_texts_clicked
    EditDialog.launch_edit_dialog()
  File "/home/milk/src/mindfulness-at-the-computer/mc/gui/rest_action_list_wt.py", line 246, in launch_edit_dialog
    dialog = EditDialog()
  File "/home/milk/src/mindfulness-at-the-computer/mc/gui/rest_action_list_wt.py", line 186, in __init__
    self.temporary_image_file_path_str = rest_action.image_path
AttributeError: 'RestActionsM' object has no attribute 'image_path'
zsh: abort (core dumped)  ./mindfulness-at-the-computer.py
```

**Comment by SunyataZero** [comment]
Woops, that was a big miss, we hadn't removed the image-related code for the rest dialog. I have now fixed this here: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/pull/312
