### ISSUE TITLE
Handle the case when there are no breathing phrases

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#95]

**Comment by yigitsever** [comment]
Furthermore:
When the breathing phrase box (and the phrases list) is empty, trying to edit or move using the buttons will crass the application:
```
TypeError: type object argument after * must be an iterable, not NoneType
[1]    11384 abort (core dumped)  python3 mindfulness-at-the-computer.py
```
**To Reproduce**

- Delete all breathing phrases using the delete button (delete button can handle empty list)
`WARNING: No phrase selected`
- When the list is empty, click any other 4 buttons to the right
![image](https://user-images.githubusercontent.com/9094218/34343658-c5a7b54e-e9e8-11e7-8da0-d05cbed6ecaf.png)

**Comment by yigitsever** [comment]
#118 addresses this issue but **does not solve** the case where the program starts with an empty phrase list

**Comment by jmlgh** [comment]
Getting the same error after deleting a single phrase (after confirmation on the pop up dialog box).

**Comment by yigitsever** [comment]
@jmlgh I was getting the same error on Manjaro Linux before #126, it's fixed now

**Comment by jmlgh** [comment]
@yigitsever Good :)
After #126, are you still having the same error as described in #95?
In my case, after deleting all phrases the buttons become deactivated. If I close and reopen the app, there are still no phrases, the buttons still show up as deactivated, and the app doesn't crash, so you're issue appears to be solved also.

**Comment by SunyataZero** [comment]
Removing all entries from the breathing phrase list and then starting the application will give the following error (which crashes the application):
```
Traceback (most recent call last):
  File "/home/sunyata/PycharmProjects/mindfulness-at-the-computer/mindfulness-at-the-computer.py", line 49, in <module>
    matc_main_window = mc.gui.main_win.MainWin()
  File "/home/sunyata/PycharmProjects/mindfulness-at-the-computer/mc/gui/main_win.py", line 70, in __init__
    self.open_breathing_dialog()
  File "/home/sunyata/PycharmProjects/mindfulness-at-the-computer/mc/gui/main_win.py", line 493, in open_breathing_dialog
    self.breathing_dialog = mc.gui.breathing_dlg.BreathingDlg()
  File "/home/sunyata/PycharmProjects/mindfulness-at-the-computer/mc/gui/breathing_dlg.py", line 43, in __init__
    self._breathing_graphicsview_l3 = GraphicsView()
  File "/home/sunyata/PycharmProjects/mindfulness-at-the-computer/mc/gui/breathing_dlg.py", line 301, in __init__
    ib_str = mc.model.PhrasesM.get(mc.mc_global.active_phrase_id_it).ib
  File "/home/sunyata/PycharmProjects/mindfulness-at-the-computer/mc/model.py", line 149, in get
    return PhrasesM(*reminder_db_te)
TypeError: type object argument after * must be an iterable, not NoneType
```
